Fixed Nullable types example in migration71/new-features.xml
Old example would actually have output:
Fatal error: Cannot redeclare testReturn()
We can also see that the output was not from real code execution because "elePHPant" should be string(9) not string(10).